// import mongoose
const mongoose = require('mongoose')

// Everything in Mongoose starts with a Schema
// Each schema maps to a MongoDB collection and
// defines the shape of the documents within that collection

// define schema
const userSchema = new mongoose.Schema({
    // id is auto generated by mongoDB
    username: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: true
    },
    roles: {
        type: [String],
        default: ['Employee']
    },
    active: {
        type: Boolean,
        default: true
    },

})

// create a data model
// User is a singular and will find its equivalent plural form in the collections from mongoDB
module.exports = mongoose.model('User', userSchema)